<!-- <fieldset id="personal-data" align="left">
<legend> <b> Персонални данни: </b> </legend> -->
<p>От град/село:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <select size="1" name="Town" tabindex="5">
        <option value="1">Айтос</option>
        <option value="2">Асеновград</option>
        <option value="3">Априлци</option>
        <option value="4">Антоново</option>
        <option value="5">Благоевград</option>
        <option value="6">Бургас</option>
        <option value="7">Банско</option>
        <option value="8">Белоградчик</option>
        <option value="9">Берковица</option>
        <option value="10">Балчик</option>
        <option value="11">Банкя</option>
        <option value="12">Батак</option>
        <option value="13">Белене</option>
        <option value="14">Бойчиновци</option>
        <option value="15">Бяла Слатина</option>
        <option value="16">Бяла (Русе)</option>
        <option value="17">Бяла (Варна)</option>
        <option value="18">Бяла Черква</option>
        <option value="19">Борово</option>
        <option value="20">Брезник</option>
        <option value="21">Бухово</option>
        <option value="22">Божурище</option>
        <option value="23">Варна</option>
        <option value="24">Велинград</option>
        <option value="25">Велико Търново</option>
        <option value="26">Враца</option>
        <option value="27">Видин</option>
        <option value="28">Вълчи Дол</option>
        <option value="29">Велики Преслав</option>
        <option value="30">Габрово</option>
        <option value="31">Горна Оряховица</option>
        <option value="32">Гоце Делчев</option>
        <option value="33">Гълъбово</option>
        <option value="34">Генерал Тошево</option>
        <option value="35">Две Могили</option>
        <option value="36">Дряново</option>
        <option value="37">Димитровград</option>
        <option value="38">Добрич</option>
        <option value="39">Дупница</option>
        <option value="40">Девин</option>
        <option value="41">Доспат</option>
        <option value="42">Долни Чифлик</option>
        <option value="43">Дунавци</option>
        <option value="44">Димово</option>
        <option value="45">Драгоман</option>
        <option value="46">Долни Дъбник</option>
        <option value="47">Долна Митрополия</option>
        <option value="48">Дулово</option>
        <option value="49">Долна Оряховица</option>
        <option value="50">Дебелец</option>
        <option value="51">Елена</option>
        <option value="52">Етрополе</option>
        <option value="53">Елин Пелин</option>
        <option value="54">Елхово</option>
        <option value="55">Златарица</option>
        <option value="56">Искър</option>
        <option value="57">Исперих</option>
        <option value="58">Каварна</option>
        <option value="59">Казанлък</option>
        <option value="60">Карлово</option>
        <option value="61">Кърджали</option>
        <option value="62">Кюстендил</option>
        <option value="63">Котел</option>
        <option value="64">Калофер</option>
        <option value="65">Китен</option>
        <option value="66">Козлодуй</option>
        <option value="67">Костинброд</option>
        <option value="68">Криводол</option>
        <option value="69">Ловеч</option>
        <option value="70">Левски</option>
        <option value="71">Летница</option>
        <option value="72">Луковит</option>
        <option value="73">Лясковец</option>
        <option value="74">Лозница</option>
        <option value="75">Монтана</option>
        <option value="76">Мелник</option>
        <option value="77">Мездра</option>
        <option value="78">Мадан</option>
        <option value="79">Нови Искър</option>
        <option value="80">Оряхово</option>
        <option value="81">Плевен</option>
        <option value="82">Полски Тръмбеш</option>
        <option value="83">Павликени</option>
        <option value="84">Правец</option>
        <option value="85">Плачковци</option>
        <option value="86">Попово</option>
        <option value="87">Русе</option>
        <option value="88">Разград</option>
        <option value="89">Свищов</option>
        <option value="90">Своге</option>
        <option value="91">Сливница</option>
        <option value="92">София</option>
        <option value="93">Севлиево</option>
        <option value="94">Стражица</option>
        <option value="95">Тръстеник</option>
        <option value="96">Тервел</option>
        <option value="97">Трън</option>
        <option value="98">Тетевен</option>
        <option value="99">Троян</option>
        <option value="100">Трявна</option>
        <option value="101">Търговище</option>
        <option value="102">Хасково</option>
        <option value="103">Харманли</option>
        <option value="104">Хисаря</option>
        <option value="105">Цар Калоян</option>
        <option value="106">Червен Бряг</option>
        <option value="107">Чипровци</option>
        <option value="108">Шумен</option>
        <option value="109">Шабла</option>
        <option value="110">Ямбол</option>
        <option value="111">Ябланица</option>
    </select></p>
</fieldset>